### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by fedaykinofdune** [anoek/webrtc-group-chat-example#1]
Very interesting project, definitely something I'd like to put to use. When I was trying to get it running I had some issues getting the dependencies, as there was no package.json and it uses an older version of express that needs certain middleware that's no longer included. I managed to get around that, but it looks like the server app wants to send a file "newclient.html" which isn't there. I made a copy of the client.html and named it newclient.html, configured and loaded the server, but all it is displaying is a blank dark grey page. Looking at the page source, its definitely receiving the page source, not sure if its something with Chrome & Firefox or what. Any ideas?

**Comment by helloncanella** [comment]
same problem

**Comment by mastershaig** [comment]
same issue

**Comment by jcarapia** [comment]
I faced the same issues. I made some modifications to the repo, especially to update some deprecations and got it to work. I made a pull request; Let me know if you have any questions - thank you.

**Comment by mastershaig** [comment]
@jcarapia Thank you for pull request, I will clone it again with your changes, will test and inform you soon !

**Comment by anoek** [comment]
Thanks for the PR @jcarapia !
