### ISSUE TITLE
I'm assuming this wont really scale?

### ISSUE THREAD

**Issue by techsin** [anoek/webrtc-group-chat-example#10]
It looks like user streams to every user connected. If so then streaming after say 5-10 users you would hit upload limit of internet?

**Comment by fritzfr** [comment]
@techsin 
I'm just reading into the topic of WebRTC group chat right now, and I was wondering the same thing. I think you are right. Looks like you need a MCU, check this: https://stackoverflow.com/a/39170787/4755172

**Comment by techsin** [comment]
Thanks didn't know that term. Helps a lot in researching.

**Comment by fritzfr** [comment]
No problem. Checkout https://github.com/jitsi/jitsi-meet too.
