### ISSUE TITLE
https etc

### ISSUE THREAD

**Issue by dirkk0** [anoek/webrtc-group-chat-example#11]
Not sure if anybody is using this, but to make it work in 2020 you need to enable https, by adding something like:

    const fs = require("fs");
    var express = require('express');
    // var http = require('http');
    const https = require("https");
    var bodyParser = require('body-parser')
    var main = express()
    // var server = http.createServer(main)

    let privateKey, certificate;

    privateKey = fs.readFileSync("selfsigned.key", "utf8");
    certificate = fs.readFileSync("selfsigned.crt", "utf8");
    const credentials = { key: privateKey, cert: certificate };
    const server = https.createServer(credentials, main);

Also, if you want to use this across multiple machines, you need to hardcode the IP where 'localhost' is.
I made a couple of minor changes (for example getting rid of https://github.com/anoek/webrtc-group-chat-example/blob/master/client.html#L45 to make the socket.io errors go away) and I can create a PR if anybody is interested.

This was the most minimal WebRTC example I could find so far, thanks for providing this. I can confirm that it works on Linux, Mac OSX and Android.

**Comment by anoek** [comment]
Thank you for this, I dropped that in and things are working well
