### ISSUE TITLE
Not working on 192.168.... :8080

### ISSUE THREAD

**Issue by reaurr** [anoek/webrtc-group-chat-example#5]
Its working on localhost:8080 but when try to access on 192.168.... :8080 it says "you choose not to provide access to camera/microphone. Demo will not work"

**Comment by talyguryn** [comment]
Had the same issue. Check your browser's settings.

![](https://capella.pics/3720e052-8ab8-47b2-b292-a20ce34d8276/resize/300) ![](https://capella.pics/5558651d-a3fd-41bd-946c-26d11e275aa8/resize/300)

**Comment by quangthi90** [comment]
I think your browser had blocked the camera & microphone because you used the not secure IP. Hope this link can help you https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339
